### ISSUE TITLE
NetworkSecurityRuleService and SubnetService are broken

### ISSUE THREAD

**Issue by djberg96** [ManageIQ/azure-armrest#147]
Upon further review I don't think these should have been made subservices. In any case, right now they don't actually work.

    sns = Azure::Armrest::Network::SubnetService.new(conf)
    sns.list('some_group)

Results in:

```
lib/azure/armrest/resource_group_based_service.rb:56:in `validate_resource_group': must specify resource group (ArgumentError)
	from /Users/dberger/Repositories/azure-armrest-djberg96/lib/azure/armrest/resource_group_based_subservice.rb:24:in `list'
```

**Comment by djberg96** [comment]
Disregard, you need to pass a virtual network name for a Subnet, and a network security group name for a NetworkSecurityRule. Code works as designed.
