### ISSUE TITLE
ResourceProviderService caching busted

### ISSUE THREAD

**Issue by djberg96** [ManageIQ/azure-armrest#177]
I'm hitting this against master. I seem to recall that we hit this before a while back @bzwei. Looks like it's returned.

```/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cache_method-0.2.7/lib/cache_method.rb:56:in `dump': singleton can't be dumped (TypeError)
	from /Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cache_method-0.2.7/lib/cache_method.rb:56:in `digest'
	from /Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cache_method-0.2.7/lib/cache_method/cached_result.rb:55:in `cache_key'
	from /Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cache_method-0.2.7/lib/cache_method/cached_result.rb:66:in `get_wrapped'
	from /Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cache_method-0.2.7/lib/cache_method/cached_result.rb:26:in `fetch'
	from /Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cache_method-0.2.7/lib/cache_method.rb:99:in `block in cache_method'
	from /Users/dberger/Repositories/azure-armrest-djberg96/lib/azure/armrest/resource_provider_service.rb:60:in `list_all'
	from providers_test.rb:12:in `<main>'```

**Comment by djberg96** [comment]
Fixed by #179
