### ISSUE TITLE
Logging test failures on Windows

### ISSUE THREAD

**Issue by djberg96** [ManageIQ/azure-armrest#259]
```
Failures:

  1) Azure::Armrest::Configuration singletons logging accepts a file name for a log
     Failure/Error: after  { File.delete(log) if File.exist?(log) }

     Errno::EACCES:
       Permission denied @ unlink_internal - azure-armrest.log
     # ./spec/configuration_spec.rb:27:in `delete'
     # ./spec/configuration_spec.rb:27:in `block (2 levels) in <top (required)>'

  2) Azure::Armrest::Configuration singletons logging accepts a file handle for a log
     Failure/Error: after  { File.delete(log) if File.exist?(log) }

     Errno::EACCES:
       Permission denied @ unlink_internal - azure-armrest.log
     # ./spec/configuration_spec.rb:27:in `delete'
     # ./spec/configuration_spec.rb:27:in `block (2 levels) in <top (required)>'

  3) Azure::Armrest::Configuration singletons logging accepts a Logger instance
     Failure/Error: after  { File.delete(log) if File.exist?(log) }

     Errno::EACCES:
       Permission denied @ unlink_internal - azure-armrest.log
     # ./spec/configuration_spec.rb:27:in `delete'
     # ./spec/configuration_spec.rb:27:in `block (2 levels) in <top (required)>'

Finished in 2.55 seconds (files took 4.32 seconds to load)
418 examples, 3 failures

Failed examples:

rspec ./spec/configuration_spec.rb:243 # Azure::Armrest::Configuration singletons logging accepts a file name for a log
rspec ./spec/configuration_spec.rb:248 # Azure::Armrest::Configuration singletons logging accepts a file handle for a log
rspec ./spec/configuration_spec.rb:255 # Azure::Armrest::Configuration singletons logging accepts a Logger instance
```
Not sure yet if this is an issue with our log handling, the specs, or the rest-client gem.

**Comment by djberg96** [comment]
BTW, this means that I'm attempting to delete a file that still has an open handle. Windows doesn't allow that. Not sure how to fix yet.

**Comment by djberg96** [comment]
Fixed by https://github.com/ManageIQ/azure-armrest/issues/267
