### ISSUE TITLE
StorageAccountService#list_all_private_images results in Errno::ECONNREFUSED

### ISSUE THREAD

**Issue by djberg96** [ManageIQ/azure-armrest#275]
On rare occasions I'm hitting an ECONNREFUSED error when attempting to use the `list_all_private_images` method. This ultimately comes from the `StorageAccount#blobs` method. I am not sure if this is an issue with the storage endpoint, or an issue with the Parallel gem and http requests.

https://github.com/ManageIQ/azure-armrest/blob/master/lib/azure/armrest/model/storage_account.rb#L277

```
/Users/djberge/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:906:in `rescue in block in connect': Failed to open TCP connection to foo.blob.core.windows.net:443 (Connection refused - connect(2) for "foo.blob.core.windows.net" port 443) (Errno::ECONNREFUSED)
	from /Users/djberge/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:903:in `block in connect'
	from /Users/djberge/.rbenv/versions/2.4.1/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
	from /Users/djberge/.rbenv/versions/2.4.1/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
	from /Users/djberge/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:902:in `connect'
	from /Users/djberge/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
	from /Users/djberge/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:876:in `start'
	from /Users/djberge/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rest-client-2.0.2/lib/restclient/request.rb:715:in `transmit'
	from /Users/djberge/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
	from /Users/djberge/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
	from /Users/djberge/Dev/azure-armrest-djberg96/lib/azure/armrest/armrest_service.rb:200:in `rest_execute'
	from /Users/djberge/Dev/azure-armrest-djberg96/lib/azure/armrest/armrest_service.rb:206:in `rest_get'
	from /Users/djberge/Dev/azure-armrest-djberg96/lib/azure/armrest/model/storage_account.rb:557:in `blob_response'
	from /Users/djberge/Dev/azure-armrest-djberg96/lib/azure/armrest/model/storage_account.rb:257:in `blobs'
	from /Users/djberge/Dev/azure-armrest-djberg96/lib/azure/armrest/model/storage_account.rb:277:in `block (2 levels) in all_blobs'
	from /Users/djberge/Dev/azure-armrest-djberg96/lib/azure/armrest/model/storage_account.rb:277:in `synchronize'
	from /Users/djberge/Dev/azure-armrest-djberg96/lib/azure/armrest/model/storage_account.rb:277:in `block in all_blobs'
	from /Users/djberge/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/parallel-1.9.0/lib/parallel.rb:453:in `call_with_index'
	from /Users/djberge/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/parallel-1.9.0/lib/parallel.rb:311:in `block (2 levels) in work_in_threads'
	from /Users/djberge/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/parallel-1.9.0/lib/parallel.rb:462:in `with_instrumentation'
	from /Users/djberge/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/parallel-1.9.0/lib/parallel.rb:310:in `block in work_in_threads'
	from /Users/djberge/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/parallel-1.9.0/lib/parallel.rb:192:in `block (2 levels) in in_threads'
```

**Comment by djberg96** [comment]
Sometimes I see timeouts instead:

```
Users/dberger/Repositories/azure-armrest-djberg96/lib/azure/armrest/armrest_service.rb:252:in `raise_api_exception': Timed out connecting to server (Azure::Armrest::OpenTimeoutException)
	from /Users/dberger/Repositories/azure-armrest-djberg96/lib/azure/armrest/armrest_service.rb:202:in `rescue in rest_execute'
	from /Users/dberger/Repositories/azure-armrest-djberg96/lib/azure/armrest/armrest_service.rb:198:in `rest_execute'
	from /Users/dberger/Repositories/azure-armrest-djberg96/lib/azure/armrest/armrest_service.rb:206:in `rest_get'
	from /Users/dberger/Repositories/azure-armrest-djberg96/lib/azure/armrest/model/storage_account.rb:560:in `blob_response'
	from /Users/dberger/Repositories/azure-armrest-djberg96/lib/azure/armrest/model/storage_account.rb:157:in `containers'
	from /Users/dberger/Repositories/azure-armrest-djberg96/lib/azure/armrest/model/storage_account.rb:279:in `all_blobs'
	from /Users/dberger/Repositories/azure-armrest-djberg96/lib/azure/armrest/storage_account_service.rb:291:in `block in get_private_images'
	from /Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/parallel-1.11.2/lib/parallel.rb:486:in `call_with_index'
	from /Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/parallel-1.11.2/lib/parallel.rb:342:in `block (2 levels) in work_in_threads'
	from /Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/parallel-1.11.2/lib/parallel.rb:495:in `with_instrumentation'
	from /Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/parallel-1.11.2/lib/parallel.rb:341:in `block in work_in_threads'
	from /Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/parallel-1.11.2/lib/parallel.rb:206:in `block (2 levels) in in_threads'
```

**Comment by djberg96** [comment]
Did what we could for now with #276
