### ISSUE TITLE
Test failures on Windows

### ISSUE THREAD

**Issue by djberg96** [ManageIQ/azure-armrest#333]
Windows 8
ruby 2.4.2p198 (2017-09-14 revision 59899) [i386-mingw32]

While not a high priority, we shouldn't be seeing test failures on any platform since this is a platform neutral library. I suspect these are issues with our specs rather than a library issue, but thought I should mention it.

```
Failures:

  1) Azure::Armrest::Configuration instances tokens token generation caches the token to be reused for the same client
     Failure/Error: expect(subject.token).to eql(token)

       expected: "Bearer eyJ0eXAiOiJKV1Q"
            got: "xxx"

       (compared using eql?)
     # ./spec/configuration_spec.rb:185:in `block (5 levels) in <top (required)>'

  2) BaseModel inspection methods defines a pretty_print method when pp is available
     Failure/Error: expect(base.pretty_inspect).to match(expected)

       expected "#<Azure::Armrest::BaseModel:0x03b95f98 name=\"test\", array=[\"stuff\"], age=33>\n" to match /\A#<Azure
::Armrest::BaseModel:0x\h+\n/
       Diff:
       @@ -1,2 +1,2 @@
       -/\A#<Azure::Armrest::BaseModel:0x\h+\n/
       +#<Azure::Armrest::BaseModel:0x03b95f98 name="test", array=["stuff"], age=33>

     # ./spec/models/base_model_spec.rb:146:in `block (3 levels) in <top (required)>'

  3) BaseModel #attr_from_hash maps it source location to the correct file
     Failure/Error: expect(subject.method(:first_name_from_hash).source_location).to include(__FILE__)
       expected ["C", 0] to include "C:/Users/Daniel/Dev/azure-armrest-djberg96/spec/models/base_model_spec.rb"
     # ./spec/models/base_model_spec.rb:291:in `block (3 levels) in <top (required)>'
     # ./spec/models/base_model_spec.rb:279:in `block (3 levels) in <top (required)>'

  4) BaseModel #attr_from_hash with multiple attributes maps it source location of each method to the correct file
     Failure/Error: expect(subject.method(:first_name_from_hash).source_location).to include(__FILE__)
       expected ["C", 0] to include "C:/Users/Daniel/Dev/azure-armrest-djberg96/spec/models/base_model_spec.rb"
     # ./spec/models/base_model_spec.rb:313:in `block (4 levels) in <top (required)>'
     # ./spec/models/base_model_spec.rb:301:in `block (4 levels) in <top (required)>'
     # ./spec/models/base_model_spec.rb:279:in `block (3 levels) in <top (required)>'

  5) BaseModel #attr_from_hash with nested attributes maps it source location to the correct file
     Failure/Error: expect(subject.method(:street_address_from_hash).source_location).to include(__FILE__)
       expected ["C", 0] to include "C:/Users/Daniel/Dev/azure-armrest-djberg96/spec/models/base_model_spec.rb"
     # ./spec/models/base_model_spec.rb:335:in `block (4 levels) in <top (required)>'
     # ./spec/models/base_model_spec.rb:324:in `block (4 levels) in <top (required)>'
     # ./spec/models/base_model_spec.rb:279:in `block (3 levels) in <top (required)>'

Finished in 1.78 seconds (files took 0.7332 seconds to load)
514 examples, 5 failures

Failed examples:

rspec ./spec/configuration_spec.rb:182 # Azure::Armrest::Configuration instances tokens token generation caches the token to be reused for the same client
rspec ./spec/models/base_model_spec.rb:142 # BaseModel inspection methods defines a pretty_print method when pp is available
rspec ./spec/models/base_model_spec.rb:290 # BaseModel #attr_from_hash maps it source location to the correct file
rspec ./spec/models/base_model_spec.rb:312 # BaseModel #attr_from_hash with multiple attributes maps it source location of each method to the correct file
rspec ./spec/models/base_model_spec.rb:334 # BaseModel #attr_from_hash with nested attributes maps it source location to the correct file
```

@NickLaMuro Looks like 3, 4 and 5 are yours.

**Comment by djberg96** [comment]
Closing, dup, github acting weird.
