### ISSUE TITLE
VirtualMachineService#delete_associated_resources does not handle managed disks

### ISSUE THREAD

**Issue by djberg96** [ManageIQ/azure-armrest#348]
At the moment if you try to call `delete_associated_resources` on a VM that uses managed storage, the storage deletion will fail. This method was originally written for unmanaged storage and was never updated.

```
undefined method 'vhd' for #<Azure::Armrest::VirtualMachineModel::Properties::StorageProfile::OsDisk:0x007fa0704c8cf0>  Method:[block in method_missing]
[----] E, [2017-11-20T15:25:51.764838 #35394:3fd03f83f7e4] ERROR -- : /Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/azure-armrest-0.9.3/lib/azure/armrest/storage_account_service.rb:197:in `get_from_vm'
/Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/azure-armrest-0.9.3/lib/azure/armrest/virtual_machine_service.rb:221:in `delete_associated_disk'
/Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/azure-armrest-0.9.3/lib/azure/armrest/virtual_machine_service.rb:165:in `delete_associated_resources'
```

**Comment by djberg96** [comment]
Fixed by https://github.com/ManageIQ/azure-armrest/pull/350
